/**
 * UserReferralService — business logic for User → User referral codes.
 *
 * Responsibilities:
 *   - Generate random referral codes (collision-safe)
 *   - Enforce daily generation limit
 *   - Validate and consume codes atomically
 *   - Prevent self-referral
 *   - Calculate code expiry from admin config
 *   - Trigger registration reward via WalletService
 *
 * Usage:
 *   const userReferralService = require('../services/userReferralService');
 */

const mongoose = require('mongoose');
const UserReferralCode = require('../models/UserReferralCode');
const User = require('../models/User');
const settings = require('../utils/settingsService');

// ── Constants ─────────────────────────────────────────────────────────────────
const MAX_GENERATION_RETRIES = 5; // retry on extremely rare code collision

// ── Helper: start of IST calendar day ────────────────────────────────────────
function getStartOfISTDay(date = new Date()) {
  // Convert to IST string, parse back, then zero out hours/minutes/seconds
  const istString = date.toLocaleString('en-US', { timeZone: 'Asia/Kolkata' });
  const istDate = new Date(istString);
  istDate.setHours(0, 0, 0, 0);
  return istDate;
}

// ── Generate a new referral code ─────────────────────────────────────────────
/**
 * Generate a new referral code for the authenticated user.
 *
 * @param {ObjectId} userId - The authenticated user's ID
 * @returns {Promise<{code: string, expiresAt: Date}>}
 * @throws {Error} If daily limit exceeded or referral system disabled
 */
async function generateCode(userId) {
  // Check if referral system is enabled
  const enabled = await settings.get('userReferralEnabled', false);
  if (!enabled) {
    throw Object.assign(new Error('User referral system is currently disabled'), { status: 403 });
  }

  // Enforce daily generation limit
  const dailyLimit = await settings.get('userReferralDailyLimit', 5);
  const startOfDay = getStartOfISTDay();
  const todayCount = await UserReferralCode.countDocuments({
    userId,
    createdAt: { $gte: startOfDay },
  });

  if (todayCount >= dailyLimit) {
    throw Object.assign(
      new Error(`Daily referral generation limit reached (${dailyLimit} per day). Try again tomorrow.`),
      { status: 429 }
    );
  }

  // Calculate expiry from admin config
  const validityDays = await settings.get('userReferralDefaultValidityDays', 30);
  const expiresAt = new Date(Date.now() + validityDays * 24 * 60 * 60 * 1000);

  // Generate a unique code with retry on collision
  let code;
  let saved = false;
  for (let attempt = 0; attempt < MAX_GENERATION_RETRIES; attempt++) {
    code = UserReferralCode.generateCode();
    try {
      const doc = await UserReferralCode.create({
        code,
        userId,
        expiresAt,
      });
      saved = true;
      return { code: doc.code, expiresAt: doc.expiresAt, referralCodeId: doc._id };
    } catch (err) {
      // Duplicate code — extremely rare; retry with a new code
      if (err.code === 11000) continue;
      throw err;
    }
  }

  throw new Error('Failed to generate a unique referral code after multiple attempts');
}

// ── List user's referral codes ───────────────────────────────────────────────
/**
 * Get all referral codes generated by the authenticated user.
 *
 * @param {ObjectId} userId
 * @param {Object} options - { page, limit }
 * @returns {Promise<{codes: Array, total: number}>}
 */
async function listUserCodes(userId, { page = 1, limit = 20 } = {}) {
  const query = { userId };

  const [codes, total] = await Promise.all([
    UserReferralCode.find(query)
      .sort({ createdAt: -1 })
      .limit(+limit)
      .skip((+page - 1) * +limit)
      .lean(),
    UserReferralCode.countDocuments(query),
  ]);

  return { codes, total, page: +page };
}

// ── Validate a referral code (for registration pre-fill) ─────────────────────
/**
 * Validate a referral code and return referrer info for registration page.
 * Does NOT consume the code — only validates existence and expiry.
 *
 * @param {string} code - The referral code to validate
 * @returns {Promise<{valid: boolean, referrerName?: string, codeId?: ObjectId}>}
 */
async function validateCode(code) {
  if (!code || typeof code !== 'string') {
    return { valid: false };
  }

  const normalizedCode = code.trim().toUpperCase();
  const referralCode = await UserReferralCode.findOne({
    code: normalizedCode,
    status: 'AVAILABLE',
  }).populate('userId', 'name');

  if (!referralCode) {
    return { valid: false };
  }

  // Check expiry
  if (referralCode.expiresAt < new Date()) {
    return { valid: false };
  }

  return {
    valid: true,
    referrerName: referralCode.userId?.name || 'Someone',
    codeId: referralCode._id,
  };
}

// ── Consume a referral code at registration (atomic) ─────────────────────────
/**
 * Atomically claim a referral code during user registration.
 *
 * MUST be called AFTER the new user has been created (newUserId required).
 * Uses findOneAndUpdate with status filter to prevent race conditions.
 * Returns null if code is already used, expired, invalid, or self-referral.
 *
 * @param {string} code - The referral code
 * @param {ObjectId} newUserId - The new user's ID (must exist in DB)
 * @returns {Promise<{referrerUserId: ObjectId, referralCodeId: ObjectId} | null>}
 */
async function consumeCode(code, newUserId) {
  if (!code || typeof code !== 'string') return null;
  if (!newUserId) return null; // safety: never consume without a real user

  const normalizedCode = code.trim().toUpperCase();

  // First, atomically claim the code — only succeeds if status is AVAILABLE
  const result = await UserReferralCode.findOneAndUpdate(
    {
      code: normalizedCode,
      status: 'AVAILABLE',
      expiresAt: { $gt: new Date() },
    },
    {
      $set: {
        status: 'USED',
        usedBy: newUserId,
        usedAt: new Date(),
      },
    },
    { new: true }
  );

  if (!result) return null;

  // Self-referral check: code owner === registering user
  if (String(result.userId) === String(newUserId)) {
    // Rollback: set back to AVAILABLE
    await UserReferralCode.findByIdAndUpdate(result._id, {
      $set: { status: 'AVAILABLE', usedBy: null, usedAt: null },
    });
    return null;
  }

  return {
    referrerUserId: result.userId,
    referralCodeId: result._id,
  };
}

// ── Check if registration reward already credited (for idempotency) ──────────
async function isRegistrationRewardCredited(referralCodeId) {
  const doc = await UserReferralCode.findById(referralCodeId).lean();
  return doc?.status === 'USED' && doc?.registrationRewardCredited === true;
}

// ── Mark registration reward as credited ─────────────────────────────────────
async function markRegistrationRewardCredited(referralCodeId) {
  await UserReferralCode.findByIdAndUpdate(referralCodeId, {
    $set: {
      registrationRewardCredited: true,
      registrationRewardCreditedAt: new Date(),
    },
  });
}

// ── Booking reward (automatic grant) ────────────────────────────────────────
const UserReferralBookingReward = require('../models/UserReferralBookingReward');
const Booking = require('../models/Booking');
const walletService = require('./walletService');

/**
 * Grant the referral booking reward when a referred user's qualifying
 * (Pooja/Kit) booking is marked COMPLETED. Called from the booking
 * completion flow; the reward is automatic — no admin approval required.
 *
 * Conditions:
 *   - booking exists and is COMPLETED
 *   - booking belongs to a user who registered via a USED UserReferralCode
 *   - the per-referred-user reward limit is not exhausted
 *   - the booking has not already generated a reward
 *
 * Idempotency:
 *   - One durable reward record per booking (unique index on bookingId).
 *   - Wallet credit uses idempotencyKey `referral_booking_reward_<recordId>`.
 *   - Slot allocation uses conditional $addToSet on the referral code's
 *     rewardedBookingIds — idempotent per booking and concurrency-safe at the
 *     configured per-referred-user maximum (single-document atomic update).
 *
 * @param {ObjectId} bookingId - The completed qualifying booking
 * @returns {Promise<{created: boolean, reward?: Document, limitReached?: boolean}>}
 */
async function createBookingRewardEligibility(bookingId) {
  // Find the booking and check it's completed
  const booking = await Booking.findById(bookingId)
    .select('userId status bookingNumber withKit')
    .lean();

  if (!booking || booking.status !== 'completed') {
    return { created: false };
  }

  // Find the referral code that linked this user (User B) to a referrer (User A)
  // The usedBy field on UserReferralCode points to User B
  const referralCode = await UserReferralCode.findOne({
    usedBy: booking.userId,
    status: 'USED',
  }).lean();

  if (!referralCode) {
    return { created: false };
  }

  // Idempotency: one reward record per booking (unique index on bookingId).
  // APPROVED/DENIED are final states; PENDING means an earlier attempt crashed
  // mid-grant, so we resume (all downstream steps are idempotent).
  let reward = await UserReferralBookingReward.findOne({ bookingId }).lean();
  if (reward && reward.status !== 'PENDING') {
    return { created: false, reward };
  }

  // Reward amount snapshot from admin config (future setting changes do not
  // rewrite historical rewards).
  const rewardAmount = await settings.get('userReferralBookingRewardCoins', 50);
  const maxLimit = await settings.get('maxRewardedBookingsPerReferredUser', 5);

  if (!reward) {
    try {
      reward = await UserReferralBookingReward.create({
        userId: referralCode.userId, // referrer (User A)
        referredUserId: booking.userId, // referred user (User B)
        referralCodeId: referralCode._id,
        bookingId: booking._id,
        bookingType: booking.withKit ? 'KIT' : 'POOJA',
        status: 'PENDING',
        rewardAmount,
      });
    } catch (err) {
      // Concurrent creation for the same booking — resume on the winner's record.
      if (err.code === 11000) {
        const dup = await UserReferralBookingReward.findOne({ bookingId }).lean();
        if (!dup) return { created: false };
        if (dup.status !== 'PENDING') return { created: false, reward: dup };
        reward = dup;
      } else {
        throw err;
      }
    }
  }

  // Limit = 0 → no booking rewards at all (registration reward unaffected).
  if (maxLimit <= 0) {
    await UserReferralBookingReward.findByIdAndUpdate(reward._id, {
      $set: { status: 'DENIED', adminNote: 'Booking reward disabled (limit set to 0)' },
    });
    return { created: true, limitReached: true, reward: await UserReferralBookingReward.findById(reward._id).lean() };
  }

  // Atomically claim a reward slot on the referral relationship.
  //   - `$addToSet` makes the claim idempotent per booking (retries never
  //     double-allocate).
  //   - The positional filter `rewardedBookingIds.<maxLimit-1>` must not exist,
  //     i.e. fewer than maxLimit entries — enforced atomically, so concurrent
  //     completions at the boundary can never exceed the limit.
  const claim = await UserReferralCode.findOneAndUpdate(
    {
      _id: referralCode._id,
      [`rewardedBookingIds.${maxLimit - 1}`]: { $exists: false },
    },
    { $addToSet: { rewardedBookingIds: booking._id } },
    { new: true }
  );

  if (!claim) {
    // Limit exhausted for this referred user — record is blocked (auditable).
    await UserReferralBookingReward.findByIdAndUpdate(reward._id, {
      $set: { status: 'DENIED', adminNote: 'Reward limit reached for this referred user' },
    });
    return { created: true, limitReached: true, reward: await UserReferralBookingReward.findById(reward._id).lean() };
  }

  // Credit the referrer's wallet through the existing ledger architecture.
  // WalletService is idempotent per idempotencyKey — concurrent duplicate
  // grants resolve to alreadyExists instead of double-crediting.
  const referredUser = await User.findById(booking.userId).select('name').lean();
  const referredName = referredUser?.name || 'Referred user';
  const bookingLabel = booking.withKit ? 'Kit' : 'Pooja';
  await walletService.credit({
    userId: referralCode.userId,
    amount: rewardAmount,
    type: 'REFERRAL_BOOKING_REWARD',
    description: `Referral Booking Reward — ${referredName}'s completed ${bookingLabel}${booking.bookingNumber ? ` (Booking #${booking.bookingNumber})` : ''}`,
    reference: { type: 'UserReferralBookingReward', id: reward._id },
    idempotencyKey: `referral_booking_reward_${reward._id}`,
  });

  // Mark approved + credited.
  const approved = await UserReferralBookingReward.findByIdAndUpdate(
    reward._id,
    {
      $set: {
        status: 'APPROVED',
        coinsCredited: true,
        coinsCreditedAt: new Date(),
        rewardAmount,
      },
    },
    { new: true }
  ).lean();

  return { created: true, reward: approved };
}

// ── Resolve referral code: new system first, then legacy ─────────────────────
/**
 * Determine which referral system matches the given code.
 * Priority: new UserReferralCode > legacy User.referralCode
 * Returns: { type: 'new', code } | { type: 'legacy', referrerId } | null
 *
 * This prevents double attribution when a code exists in both systems.
 */
async function resolveReferralCode(code) {
  if (!code || typeof code !== 'string') return null;

  const normalizedCode = code.trim().toUpperCase();

  // Check new system first (authoritative for new referrals)
  const referralEnabled = await settings.get('userReferralEnabled', false);
  if (referralEnabled) {
    const newCode = await UserReferralCode.findOne({
      code: normalizedCode,
      status: 'AVAILABLE',
      expiresAt: { $gt: new Date() },
    }).lean();
    if (newCode) {
      return { type: 'new', code: newCode };
    }
  }

  // Fall back to legacy system
  const legacyReferrer = await User.findOne({
    referralCode: normalizedCode,
  }).select('_id').lean();
  if (legacyReferrer) {
    return { type: 'legacy', referrerId: legacyReferrer._id };
  }

  return null;
}

module.exports = {
  generateCode,
  listUserCodes,
  validateCode,
  consumeCode,
  isRegistrationRewardCredited,
  markRegistrationRewardCredited,
  getStartOfISTDay,
  createBookingRewardEligibility,
  resolveReferralCode,
};
